# Generated by Django 5.2.15 on 2026-07-14 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Colaboradores",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="OrdemServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_cliente",
                    models.CharField(max_length=200, verbose_name="Nome do cliente"),
                ),
                ("telefone", models.CharField(blank=True, default="", max_length=20)),
                ("marca", models.CharField(blank=True, default="", max_length=50)),
                ("modelo", models.CharField(blank=True, default="", max_length=80)),
                ("placa", models.CharField(max_length=10)),
                (
                    "km",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="KM do veículo"
                    ),
                ),
                (
                    "servico",
                    models.CharField(max_length=200, verbose_name="Tipo de serviço"),
                ),
                ("data", models.DateField(verbose_name="Data do serviço")),
                (
                    "garantia_dias",
                    models.PositiveIntegerField(
                        default=90, verbose_name="Garantia (dias)"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Descrição / serviços realizados",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor cobrado",
                    ),
                ),
                (
                    "material",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Custo de material",
                    ),
                ),
                (
                    "comissao",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Comissão",
                    ),
                ),
                (
                    "pagamento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Dinheiro", "Dinheiro"),
                            ("PIX", "PIX"),
                            ("Cartão crédito", "Cartão crédito"),
                            ("Cartão débito", "Cartão débito"),
                            ("Transferência", "Transferência"),
                            ("Fiado", "Fiado"),
                        ],
                        default="",
                        max_length=30,
                        verbose_name="Forma de pagamento",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Aberta", "Aberta"),
                            ("Em andamento", "Em andamento"),
                            ("Concluída", "Concluída"),
                            ("Garantia", "Garantia"),
                        ],
                        default="Concluída",
                        max_length=20,
                    ),
                ),
                ("checklist", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "colaborador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gestao.colaborador",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de Serviço",
                "verbose_name_plural": "Ordens de Serviço",
                "ordering": ["-data", "-criado_em"],
            },
        ),
    ]
