# Generated by Django 5.2.15 on 2026-07-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContaPagar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Salário", "Salário"),
                            ("Boleto", "Boleto"),
                            ("Dívida", "Dívida"),
                            ("Imposto", "Imposto"),
                            ("Fornecedor", "Fornecedor"),
                            ("Aluguel", "Aluguel"),
                            ("Água/Luz/Internet", "Água/Luz/Internet"),
                            ("Outros", "Outros"),
                        ],
                        default="Boleto",
                        max_length=30,
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor (R$)",
                    ),
                ),
                ("vencimento", models.DateField(verbose_name="Data de vencimento")),
                ("pago", models.BooleanField(default=False, verbose_name="Pago")),
                (
                    "observacao",
                    models.TextField(blank=True, default="", verbose_name="Observação"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Conta a Pagar",
                "verbose_name_plural": "Contas a Pagar",
                "ordering": ["vencimento", "id"],
            },
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="servico",
            field=models.TextField(verbose_name="Serviços realizados"),
        ),
    ]
