# Generated by Django 5.2.15 on 2026-07-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0002_contapagar_alter_ordemservico_servico"),
    ]

    operations = [
        migrations.AddField(
            model_name="contapagar",
            name="grupo",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="contapagar",
            name="recorrencia",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Única (sem repetição)"),
                    ("Diária", "Diária"),
                    ("Semanal", "Semanal"),
                    ("Mensal", "Mensal"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
