# Generated by Django 5.2.15 on 2026-07-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0003_contapagar_grupo_contapagar_recorrencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, unique=True, verbose_name="Nome"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("3ª Geração", "3ª Geração"),
                            ("5ª Geração", "5ª Geração"),
                            ("Componentes", "Componentes"),
                            ("Geral", "Geral"),
                            ("Outros", "Outros"),
                        ],
                        default="Outros",
                        max_length=20,
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor cobrado (R$)",
                    ),
                ),
                (
                    "custo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Custo (R$)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Serviços",
                "ordering": ["categoria", "nome"],
            },
        ),
    ]
